org: neverfeartheashere
app: plants-api

service:
  name: plants-api

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  register:
    handler: handler.registerPushToken
    events:
      - http:
          method: post
          path: register

  sendNotification:
    handler: handler.sendNotification
    events:
      - http:
          method: post
          path: send-notification
